services:
  a4s-gateway:
    image: nginx:1.27-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      - A4S_API_URL=http://a4s-api:8000
      - NGINX_ENVSUBST_FILTER=A4S_API_URL
    depends_on:
      - a4s-api
    networks:
      - a4s-network

  lunarr:
    build:
      context: ./lunarr
      dockerfile: Dockerfile
      args:
        - API_BASE_URL=http://localhost:8080
    ports:
      - "8081:80"
    depends_on:
      - a4s-gateway
    networks:
      - a4s-network

  a4s-api:
    # Force x86_64 for sqlite-vec compatibility on Apple Silicon.
    # Remove if sqlite-vec adds proper ARM64 Linux wheels.
    platform: linux/amd64
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    user: root
    env_file:
      - api/.env
    environment:
      - API_BASE_URL=http://a4s-api:8000
      - AGENT_GATEWAY_URL=http://a4s-gateway:8080
      - AGENT_NETWORK=a4s-network
      - QDRANT_URL=http://a4s-registry:6333
      - GRAPHITI_FALKORDB_HOST=a4s-memory
      - 'CORS_ORIGINS=["http://localhost:3000", "http://localhost:5173", "http://localhost:8080", "http://localhost:8081"]'
      - SKILLS_DB_PATH=/app/data/skills.db
      - CHANNEL_DB_PATH=/app/data/channels.db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - model-cache:/root/.cache
      - api-data:/app/data
    depends_on:
      - a4s-registry
      - a4s-memory
    networks:
      - a4s-network

  a4s-registry:
    image: qdrant/qdrant:v1.16
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/data
    networks:
      - a4s-network

  a4s-memory:
    image: falkordb/falkordb:v4.16.0
    ports:
      - "6379:6379"
      - "3000:3000"
    volumes:
      - falkordb-data:/data
    networks:
      - a4s-network

  a4s-backbone:
    container_name: a4s-agent-backbone-router
    platform: linux/amd64
    build:
      context: .
      dockerfile: agents/personal-assistant/Dockerfile
    env_file:
      - api/.env
    environment:
      AGENT_NAME: backbone_router
      AGENT_ID: backbone-router
      AGENT_HOST: a4s-agent-backbone-router
      AGENT_MCP_TOOL_FILTER: search_agents,send_a2a_message
      AGENT_MODEL_PROVIDER: ${BACKBONE_AGENT_MODEL_PROVIDER:-openrouter}
      AGENT_MODEL_ID: ${BACKBONE_AGENT_MODEL_ID:-google/gemini-3-flash-preview}
      AGENT_TOOLS: ""
      A4S_API_URL: http://a4s-api:8000
      A4S_AGENT_URL: http://a4s-gateway:8080/agents/backbone-router/
      AGENT_INSTRUCTION: |
        You are a routing agent for channels. You receive user messages with channel context.

        PHASE 1 - ROUTING:
        When you receive a message with available agents listed:
        1. Analyze the user's message
        2. Call search_agents with the user's query AND the channel_id provided in context
        3. Return ONLY a JSON object: {"candidates": [{"id": "...", "name": "...", "reason": "..."}]}
        4. If no agents are relevant and you can answer directly, respond with plain text

        PHASE 2 - FORWARDING:
        When you receive a message with approved agent IDs:
        1. Call send_a2a_message for EACH approved agent in a single turn (parallel tool calls)
        2. Return ONLY the tool results as-is (do not summarize or modify)

        Response format rules:
        - For routing: always return {"candidates": [...]} as raw JSON, no markdown
        - For forwarding: always return {"results": [...]} as raw JSON, no markdown
        - For direct answers: return plain text only
    depends_on:
      - a4s-api
    networks:
      - a4s-network

networks:
  a4s-network:
    name: a4s-network

volumes:
  qdrant-data:
  falkordb-data:
  # Model cache for fastembed
  model-cache:
  # SQLite data for skills and channels
  api-data:
